apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  tester
  labels:
    name:  tester
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  tester
    spec:
      containers:
      - image: microsoft/aci-helloworld
        imagePullPolicy: Always
        name: helloworld
        resources:
          requests:
            memory: 1G
            cpu: 1
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
      - key: azure.com/aci
        effect: NoSchedule