apiVersion: '2018-10-01'
location: eastus
name: scheduler
properties:
  containers:
  - name: scheduler
    properties:
      command:
      - /scheduler
      - --leader-elect=true
      - --master=http://$API_SERVER_IP:6445
      - --v=2
      environmentVariables: []
      image: gcr.io/google-containers/hyperkube-amd64:v1.9.2
      ports: []
      resources:
        requests:
          cpu: 1.0
          memoryInGB: 1.5
  osType: Linux
  restartPolicy: Always
tags: {}
type: Microsoft.ContainerInstance/containerGroups